### ISSUE TITLE
Switch the site generator from Hugo to Quarto

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/website#32]
I would like to renew the web site with the following steps

- [x] Ignore the `docs` dir (#33)
- [x] Switch the Hugo build execution from Netlify to GitHub Actions and verify that it deploys successfully (#34)
- [x] Change the build command in the workflow from `hugo` to `quarto render` (At this point, the build is expected to fail because `_quarto.yml` is not included yet) (#37)
- [x] Switch the contents from Hugo to Quarto (#44)

**Comment by eitsupi** [comment]
After #34 (and some fixes by #38, #40) and setting the secrets (thanks @cboettig !), deploying via GitHub Actions seems to work.

But, the preview seems not created for PRs from forked repositories. (Compare #39 and #41)

I am not familiar with Environment, but perhaps the forked repository does not have access to the secrets set in Environments?
I would appreciate your opinion on whether to leave it as is or resolve this issue. Thank you.

**Comment by eddelbuettel** [comment]
> I am not familiar with Environment, but perhaps the forked repository does not have access to the secrets set in Environments?

Yes I believe that to be documented.

**Comment by eitsupi** [comment]
Thanks.
I am a little reluctant to not be able to use the preview for PRs from forks, but for now I would like to proceed as is.

**Comment by eitsupi** [comment]
Closed by #44.
