### ISSUE TITLE
More contents...

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/website#35]
I'll write it down so I don't forget.

- [x] Update rocker/rstudio with docker compose (rocker-org/rocker-versioned2#464, rocker-org/rocker-versioned2#396, etc.)
- [x] More image listing (#47)
- [x] IDEs
  - [x] mybinder
  - [x] VSCode
- [x] Other projects (rocker-org/rocker#492)
- [x] Docker settings
  - [x] Proxy (rocker-org/rocker-versioned2#462 etc.)
  - [x] Bind mount (rocker-org/rocker-versioned2#229, rocker-org/rocker-versioned2#489 etc.)
- [x] Update about BLAS (rocker-org/rocker-versioned2#471)
- [x] About RSPM (rocker-org/rocker-versioned2#476, etc.)
- [x] Link to papers (https://journal.r-project.org/archive/2017/RJ-2017-065/index.html, https://journal.r-project.org/archive/2020/RJ-2020-007/index.html)

**Comment by eitsupi** [comment]
Done.
